version: '3.7'
services:
  prod:
    container_name: ixo-did-resolver
    image: ghcr.io/ixofoundation/ixo-did-resolver:latest
    restart: unless-stopped
    ports:
      - 8080:8080
  dev:
    container_name: ixo-did-resolver-dev
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    image: ixo-did-resolver:dev
    restart: unless-stopped
    volumes:
      - ./:/app
    ports:
      - 8081:8081
