version: '3.7'
services:
  ixo-did-resolver:
    container_name: ixo-did-resolver
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    image: ixo-did-resolver
    restart: unless-stopped
    volumes:
      - ./:/app
    ports:
      - '8080:8080'
